site_name: greenh47
site_url: https://example.com/
repo_url: https://github.com/GreenH47/mynote
site_description: greenh47 personal website
site_author: greenh47
nav:
    - Home: index.md
    - 'About': 
        - 'blog index': 'about/about_index.md'
        - 'about me': 'about/about_me.md'
        - 'How to build this site': 'about/about_site_building.md'
        - 'Power by and copyright': 'about/about_copyright.md'
        
    - 'Course Study Note':
        - 'Course study note navigation': 'course_notes/course_note_menu.md'
        - 'FIT9132 Introduction to databases 2022 s1': 'course_notes/fit9132.md'
        - 'FIT5032 Asp .net develop 2022 s2': 'course_notes/fit5032.md'
        - 'FIT5057 project management 2022 s2': 'course_notes/fit5057.md'
        - 'FIT5125 IT research methods 2022 s2': 'course_notes/fit5125.md'
        - 'FIT5136 software engineering 2022 s2': 'course_notes/fit5136.md'
        - 'CS 61A: Structure and Interpretation of Computer Programs': 'course_notes/cs61a.md'
        - 'FIT5225 Cloud computing and security 2023 s1': 'course_notes/fit5225.md'
        - 'FIT5225 assignment 2023 s1': 'course_notes/fit5225_note.md'
        - 'FIT5147 Data exploration and visualisation 2023 s1': 'course_notes/fit5147.md'
        - 'FIT5147 R intro 2023 s1': 'course_notes/Rintro.md'
        - 'FIT5046 Mobile and distributed computing systems 2023 s1': 'course_notes/fit5046.md'
        - 'FIT5046 assignment 2023 s1': 'course_notes/fit5046_assignment.md'
        - 'FIT5171 System validation and verification, quality and standards 2023 s1': 'course_notes/fit5171.md'
        
        
        
    - 'Programming Note':
        - 'CSS':
            - 'CSS  note navigation': "CSS/CSS_note_menu.md"
        - 'HTML':
            - 'HTML note navigation': "HTML/HTML_note_menu.md"
            - 'HTML get started': "HTML/HTML_started.md"
        - ' Git branching learning': 'Git/Git.md'
        - 'LeetCode':
            - 'LeetCode note navigation': "LeetCode/LeetCode_note_menu.md"
        - 'Javascript ':
            - 'javascript  note navigation': "Javascript/Javascript_note_menu.md"
        - 'reactJS':
            - 'reactJS note navigation': "reactJS/react_note_menu.md"
            
    - 'Career Note':
        - 'career note navigation': 'career/career_note_menu.md'
        - '2023 summer casual': 'career/career_23summer.md'
        
    - 'Green chat':
        - 'Green chat navigation': 'chat/chat_index.md'
        - '221206_ChatGPT': 'chat/221206_ChatGPT.md'
        - '230521_serverless,microservices,RESTFUL': 'chat/230521_serverless,microservices,RESTFUL.md'
        
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - toc.follow


  
markdown_extensions:
    - def_list
    - toc:
        permalink: "#"
        baselevel: 2
plugins:
  - search:
        indexing: 'full'
        separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/GreenH47
    - icon: fontawesome/solid/paper-plane
      link: mailto:greenhuang47@gmail.com
      
copyright: Copyright &copy; 2021 - present GreenH47

