site_name: greenh47
site_url: https://example.com/
repo_url: https://github.com/GreenH47/mynote
site_description: greenh47 personal website
site_author: greenh47
nav:
    - Home: index.md
    - 'About': 
        - 'about me': 'about/about_me.md'
        - 'How to build this site': 'about/about_site_building.md'
        - 'Power by and copyright': 'about/about_copyright.md'
        
    - 'FIT Study Note':
        - 'FIT5032 Asp .net develop 2022 s2': 'fitnotes/fit5032.md'
        - 'FIT5057 project management 2022 s2': 'fitnotes/fit5057.md'
        - 'FIT5136 software engineering 2022 s2': 'fitnotes/fit5136.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - toc.follow


markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
plugins:
  - search:
        indexing: 'full'
        separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/GreenH47
    - icon: fontawesome/solid/paper-plane
      link: mailto:greenhuang47@gmail.com
      
copyright: Copyright &copy; 2021 - present GreenH47

